### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by delbertaud** [eljefe7000/RestApiToText#5]
It might be nice to add variables in the supplied inputs for header values. These inputs would pull values from environment variables for security reasons. An example of such might be:

**Headers**
Auth-Key: --testSystemAuthKey--

The code would retrieve the testSystemAuthKey from the OS Environment variables and replace the provided tag. This would reduce the security risk as sensitive information would not be visible or saved in rest documentation files.

**Comment by eljefe7000** [comment]
Hi  Delbert,
That sounds like a great idea.  Let me see what I can do.  Thanks for the
suggestion.

**Comment by eljefe7000** [comment]
Hi Delbert,
I was able to implement your idea of using environment variables.  I designed the syntax so that it would appear as an expression.  I added the "env:" piece in case someone might add a feature suggestion to read from another location in the future, like the Registry.  The syntax is below.  Can you please give it try?  Here are the [32-bit](https://github.com/eljefe7000/RestApiToText/raw/master/Release/v1.3.1.0/RestApiToText.zip) and [64-bit](https://github.com/eljefe7000/RestApiToText/raw/master/x64/Release/v1.3.1.0/RestApiToText.zip) for your convenience.  Thanks again for your suggestion.

Auth-Key: $(env:testSystemAuthKey)

**Comment by delbertaud** [comment]
Fabulous, Big thank you for adding the security feature of allowing sensitive information to be saved elsewhere. Leveraging on your idea you might want to support the ability to have such data in a file. This way one can place variables in an ini file and then you read the ini file and allow use with variables. Have you setup a donation place where people can make donations to support your efforts? Sometimes $20 here and $20 there is a nice thank you.

**Comment by eljefe7000** [comment]
No worries.  I'm glad it works for you.  And having a central INI/JSON/Config file to store variables is a good idea also.  I will research it and get back to you.  I have a PayPal account and I've thought about including a link to it in the project and on the About page, so maybe I will do that.  Thanks!

**Comment by dm64emis** [comment]
Hi, any chance you could extend the use of environment variables to the Url and body text also? I'm testing a rest call with content-type: application/x-www-form-urlencoded and the body has username + password. It would be good to be able to hide these values from view.

You could have a querystring with sensitive data also

Nice extension by the way.
thanks

**Comment by eljefe7000** [comment]
Hi @dm64emis ,

Thanks!  It seems pretty straightforward in theory.  Let me take a look at the code and get back to you.

**Comment by eljefe7000** [comment]
Hi @dm64emis,

Sorry for getting back so late, but my day job has taken most of my time for the past few months.  I have made the changes and I'm going through testing now.

**Comment by eljefe7000** [comment]
Hi @dm64emis,

Once again, my apologies for the late response.  I have added the feature to include environment variables in the body and URL.  If you're still interested, you can download the latest DLL from the release folders in the repo.  Thanks for the suggestion!
