### ISSUE TITLE
Cannot install on 64bit Npp

### ISSUE THREAD

**Issue by endo64** [eljefe7000/RestApiToText#6]
Installation failed on 64bit version of Notepad++, any plan to support?

**Comment by endo64** [comment]
NPP keeps asking to remove `RestApiToText.dll` but it stays. I manually deleted the file.

![image](https://user-images.githubusercontent.com/840604/125592902-1ff08eda-47e3-47f1-9358-235e92ef8717.png)

**Comment by eljefe7000** [comment]
Hi Semseddin,

Thank you for pointing this out, but I am unable to reproduce the issue
(please see below).  Are you running Notepad++ v8?  That is what I'm
using.  After seeing your email, I downloaded and installed the 64bit
version of Notepad++ v8, then added the RestApiToText package, and was able
to use it.
[image: image.png]
[image: image.png]

**Comment by eljefe7000** [comment]
Hi Semseddin,
I replied via Gmail earlier and I see that my screenshots were not transferred here.  So here are some screenshots of a RestApiToText call that I made after installing Notepad++ v8 64bit.  I downloaded RestApiToText via the Plugin Manager and it worked without error.  Debug info for my installation of Notepad++ is at the bottom.
![image](https://user-images.githubusercontent.com/10099377/125666623-f7f0194a-973e-4945-847e-668527c5cf38.png)
![image](https://user-images.githubusercontent.com/10099377/125666752-f0d11d2d-c031-402a-9eec-37fbac8c7f64.png)
![image](https://user-images.githubusercontent.com/10099377/125666939-cf56ae65-0d70-4a7c-9962-266a06d02b82.png)

Notepad++ v8   (64-bit)
Build time : Jun  6 2021 - 18:38:25
Path : C:\Program Files\Notepad++\notepad++.exe
Command Line : 
Admin mode : OFF
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Pro for Workstations (64-bit) 
OS Version : 1903
OS Build : 18362.1256
Current ANSI codepage : 1252
Plugins : mimeTools.dll NppConverter.dll NppExport.dll

**Comment by endo64** [comment]
Sorry for the delay I didn't see the notification on Github;
I just tested on NPP v8.1.1 (x86 - 32bit), it worked. I'll test with x64 version (on another PC) and let you know the result.

**Comment by eljefe7000** [comment]
@endo64 , No worries.  Hopefully v8.1.1 will work for you.  Thanks!

**Comment by endo64** [comment]
Interesting I still have the same issue on my x64 PC.

Npp v8.1.2
RestApiToText 1.3.1

![image](https://user-images.githubusercontent.com/840604/127126253-fe44fd9b-448c-45ea-88c5-a8fcab346a8d.png)

![image](https://user-images.githubusercontent.com/840604/127126305-036e8bfc-9677-4b25-bf41-fbfb4c8aad88.png)

It might be MSVC runtime (v14) it requires, but actually it is installed on my PC

![image](https://user-images.githubusercontent.com/840604/127127303-c581afab-4072-4716-8961-cd015b0efea5.png)

Npp can remove the plugin if I start Npp as administrator.

**Comment by eljefe7000** [comment]
Hi @endo64 , 

Sorry for getting back so late.  It's been a busy week at my day job :-)

How are you installing the DLL?  Are you getting it via the Plugin Admin or are you downloading it directly from this repository?  Also, can you please post the debug info for your installation of NPP?

Thanks,
Jeff

**Comment by Beercow** [comment]
Ran into this with other plugins on a new build myself. You need to install microsoft visual c++ redistributable

**Comment by endo64** [comment]
I tested it worked. I'm on Npp v8.1.9.3 (x64), so may be the issue solved on recent versions of Npp.
I'll test it on another PC to be sure.

@eljefe7000 I installed it using Plugin Admin.

@Beercow MSVC runtime (v14) installed on my PC, which version does it require?

**Comment by endo64** [comment]
> I'll test it on another PC to be sure.

I've tested on a different PC (Win10 x64) it works now.
Probably latest version of Npp or Window updates solves the issue, I'm closing the issue as I cannot reproduce it anymore.
